backend=qilin
label=dacapo2006-eclipse-qilin
appPath=benchmarks/dacapo2006/eclipse.jar
libraries=benchmarks/dacapo2006/eclipse-deps.jar
mainClass=dacapo.eclipse.Main
jre=benchmarks/JREs/jre1.6.0_45
reflectionLog=benchmarks/dacapo2006/eclipse-refl.log
aliasing=pts
threads=1
qilinFlags=-pae -pe -clinit=ONFLY -lcs -mh -pta=insens
sources=benchmarks/definitions/dacapo-eclipse-example-sources.txt
sinks=benchmarks/definitions/dacapo-eclipse-example-sinks.txt
output=results/dacapo-eclipse-qilin.txt
