backend=qilin
label=flowdroid-official-constant-easy-var-qilin
appPath=build/flowdroid-official/constant/flowdroid-official-constant-selected.jar
mainClass=dev.qilinfd.bench.flowdroid.ConstantTestHarness
jre=benchmarks/JREs/jre1.8.0_121_debug
aliasing=pts
threads=1
qilinFlags=-pae -pe -clinit=ONFLY -lcs -mh -se -pta=insens
sources=benchmarks/definitions/flowdroid-official-constant-sources.txt
sinks=benchmarks/definitions/flowdroid-official-constant-sinks.txt
output=results/flowdroid-official-constant-qilin.txt
