backend=qilin
label=github-owasp-benchmark-xss-00380
appPath=build/github/owasp-benchmark/owasp-benchmark-xss-selected.jar
libraries=build/github/owasp-benchmark/lib
mainClass=org.owasp.benchmark.testcode.BenchmarkTest00380Harness
jre=benchmarks/JREs/jre1.8.0_121_debug
aliasing=pts
threads=1
qilinFlags=-pae -pe -clinit=ONFLY -lcs -mh -se -pta=insens
sources=benchmarks/definitions/github-owasp-benchmark-xss-sources.txt
sinks=benchmarks/definitions/github-owasp-benchmark-xss-sinks.txt
output=results/github-owasp-benchmark-xss.txt
