backend=qilin
label=github-juliet-cwe78-environment-01
appPath=build/github/juliet/juliet-cwe78-environment-selected.jar
libraries=benchmarks/github/juliet-test-suite/lib/servlet-api.jar
mainClass=testcases.CWE78_OS_Command_Injection.CWE78EnvironmentHarness
jre=benchmarks/JREs/jre1.8.0_121_debug
aliasing=pts
threads=1
qilinFlags=-pae -pe -clinit=ONFLY -lcs -mh -se -pta=insens
sources=benchmarks/definitions/github-juliet-cwe78-sources.txt
sinks=benchmarks/definitions/github-juliet-cwe78-sinks.txt
output=results/github-juliet-cwe78.txt
