backend=qilin
label=github-vulnerable-app-command-level1
appPath=build/github/vulnerable-app/vulnerable-app-command-selected.jar
libraries=build/github/vulnerable-app/lib
mainClass=org.sasanlabs.analysis.CommandInjectionHarness
jre=benchmarks/JREs/jre1.8.0_121_debug
aliasing=pts
threads=1
qilinFlags=-pae -pe -clinit=ONFLY -lcs -mh -se -pta=insens
sources=benchmarks/definitions/github-vulnerable-app-command-sources.txt
sinks=benchmarks/definitions/github-vulnerable-app-command-sinks.txt
output=results/github-vulnerable-app-command.txt
