backend=qilin
label=github-owasp-benchmark-xss-00380
mainClass=org.owasp.benchmark.testcode.BenchmarkTest00380Harness
pta=insens
callgraphMode=qilin
aliasing=pts
threads=1
sources=benchmarks/definitions/github-owasp-benchmark-xss-sources.txt
sinks=benchmarks/definitions/github-owasp-benchmark-xss-sinks.txt
