backend=qilin
label=securibench-basic1-qilin
mainClass=securibench.micro.basic.Basic1Harness
pta=insens
callgraphMode=qilin
aliasing=pts
threads=1
sources=benchmarks/definitions/securibench-sources.txt
sinks=benchmarks/definitions/securibench-sinks.txt
