backend=qilin
label=securibench-basic1-qilin
appPath=build/securibench/securibench-micro-harness.jar
libraries=benchmarks/securibench-micro/lib
mainClass=securibench.micro.basic.Basic1Harness
jre=benchmarks/JREs/jre1.8.0_121_debug
aliasing=pts
threads=1
qilinFlags=-pae -pe -clinit=ONFLY -lcs -mh -se -pta=insens
sources=benchmarks/definitions/securibench-sources.txt
sinks=benchmarks/definitions/securibench-sinks.txt
output=results/securibench-basic1-qilin.txt
